// models/pays_model.dart
class Pays {
  final String nom;
  final String capitale;

  Pays({required this.nom, required this.capitale});
}

List<Pays> paysArabes = [
  // Afrique (54)
  Pays(nom: 'الجزائر', capitale: 'الجزائر'),
  Pays(nom: 'أنغولا', capitale: 'لواندا'),
  Pays(nom: 'بنين', capitale: 'بورتو نوفو'),
  Pays(nom: 'بوتسوانا', capitale: 'غاتيسونيغ'),
  Pays(nom: 'بوركينا فاسو', capitale: 'واغادوغو'),
  Pays(nom: 'بوروندي', capitale: 'غيتغا'),
  Pays(nom: 'الرأس الأخضر', capitale: 'برايا'),
  Pays(nom: 'الكاميرون', capitale: 'ياوندي'),
  Pays(nom: 'جمهورية إفريقيا الوسطى', capitale: 'بانغي'),
  Pays(nom: 'تشاد', capitale: 'نجامينا'),
  Pays(nom: 'جزر القمر', capitale: 'موروني'),
  Pays(nom: 'الكونغو', capitale: 'برازافيل'),
  Pays(nom: 'الكونغو الديمقراطية', capitale: 'كينشاسا'),
  Pays(nom: 'ساحل العاج', capitale: 'ياموسوكرو'),
  Pays(nom: 'جيبوتي', capitale: 'جيبوتي'),
  Pays(nom: 'مصر', capitale: 'القاهرة'),
  Pays(nom: 'غينيا الاستوائية', capitale: 'مالابو'),
  Pays(nom: 'إريتريا', capitale: 'أسمرة'),
  Pays(nom: 'أثيوبيا', capitale: 'أديس أبابا'),
  Pays(nom: 'الغابون', capitale: 'ليبرفيل'),
  Pays(nom: 'غامبيا', capitale: 'بانجول'),
  Pays(nom: 'غانا', capitale: 'أكرا'),
  Pays(nom: 'غينيا', capitale: 'كوناكري'),
  Pays(nom: 'غينيا بيساو', capitale: 'بيساو'),
  Pays(nom: 'كينيا', capitale: 'نيروبي'),
  Pays(nom: 'ليسوتو', capitale: 'ماسيرو'),
  Pays(nom: 'ليبيريا', capitale: 'مونروفيا'),
  Pays(nom: 'ليبيا', capitale: 'طرابلس'),
  Pays(nom: 'مدغشقر', capitale: 'أنتاناناريفو'),
  Pays(nom: 'مالاوي', capitale: 'ليلونغوي'),
  Pays(nom: 'مالي', capitale: 'باماكو'),
  Pays(nom: 'موريتانيا', capitale: 'نواكشوط'),
  Pays(nom: 'موريشيوس', capitale: 'بورت لويس'),
  Pays(nom: 'المغرب', capitale: 'الرباط'),
  Pays(nom: 'موزمبيق', capitale: 'مابوتو'),
  Pays(nom: 'ناميبيا', capitale: 'ويندهوك'),
  Pays(nom: 'النيجر', capitale: 'نيامي'),
  Pays(nom: 'نيجيريا', capitale: 'أبوجا'),
  Pays(nom: 'رواندا', capitale: 'كيغالي'),
  Pays(nom: 'ساو تومي وبرينسيب', capitale: 'ساو تومي'),
  Pays(nom: 'السنغال', capitale: 'داكار'),
  Pays(nom: 'سيشيل', capitale: 'فيكتوريا'),
  Pays(nom: 'سيراليون', capitale: 'فريتاون'),
  Pays(nom: 'الصومال', capitale: 'مقديشو'),
  Pays(nom: 'جنوب إفريقيا', capitale: 'بريتوريا'),
  Pays(nom: 'جنوب السودان', capitale: 'جوبا'),
  Pays(nom: 'السودان', capitale: 'الخرطوم'),
  Pays(nom: 'تنزانيا', capitale: 'دودوما'),
  Pays(nom: 'توغو', capitale: 'لومي'),
  Pays(nom: 'تونس', capitale: 'تونس'),
  Pays(nom: 'أوغندا', capitale: 'كمبالا'),
  Pays(nom: 'زامبيا', capitale: 'لوساكا'),
  Pays(nom: 'زيمبابوي', capitale: 'هراري'),

  // آسيا (49)
  Pays(nom: 'أفغانستان', capitale: 'كابول'),
  Pays(nom: 'السعودية', capitale: 'الرياض'),
  Pays(nom: 'أرمينيا', capitale: 'يريفان'),
  Pays(nom: 'أذربيجان', capitale: 'باكو'),
  Pays(nom: 'البحرين', capitale: 'المنامة'),
  Pays(nom: 'بنغلاديش', capitale: 'دكا'),
  Pays(nom: 'بوتان', capitale: 'تيمفو'),
  Pays(nom: 'بروناي', capitale: 'بندر سيري'),
  Pays(nom: 'كمبوديا', capitale: 'بنوم بنه'),
  Pays(nom: 'الصين', capitale: 'بكين'),
  Pays(nom: 'قبرص', capitale: 'نيقوسيا'),
  Pays(nom: 'جورجيا', capitale: 'تبليسي'),
  Pays(nom: 'الهند', capitale: 'نيودلهي'),
  Pays(nom: 'إندونيسيا', capitale: 'جاكرتا'),
  Pays(nom: 'إيران', capitale: 'طهران'),
  Pays(nom: 'العراق', capitale: 'بغداد'),
  Pays(nom: 'إسرائيل', capitale: 'تل أبيب'),
  Pays(nom: 'اليابان', capitale: 'طوكيو'),
  Pays(nom: 'الأردن', capitale: 'عمّان'),
  Pays(nom: 'كازاخستان', capitale: 'أستانا'),
  Pays(nom: 'الكويت', capitale: 'الكويت'),
  Pays(nom: 'قرغيزستان', capitale: 'بيشكك'),
  Pays(nom: 'لاوس', capitale: 'فيانتيان'),
  Pays(nom: 'لبنان', capitale: 'بيروت'),
  Pays(nom: 'ماليزيا', capitale: 'كوالالمبور'),
  Pays(nom: 'المالديف', capitale: 'ماليه'),
  Pays(nom: 'منغوليا', capitale: 'أولان باتور'),
  Pays(nom: 'ميانمار', capitale: 'نايبيداو'),
  Pays(nom: 'نيبال', capitale: 'كاتماندو'),
  Pays(nom: 'كوريا الشمالية', capitale: 'بيونغيانغ'),
  Pays(nom: 'عُمان', capitale: 'مسقط'),
  Pays(nom: 'باكستان', capitale: 'إسلام آباد'),
  Pays(nom: 'فلسطين', capitale: 'القدس الشرقية'),
  Pays(nom: 'الفلبين', capitale: 'مانيلا'),
  Pays(nom: 'قطر', capitale: 'الدوحة'),
  Pays(nom: 'كوريا الجنوبية', capitale: 'سيول'),
  Pays(nom: 'سنغافورة', capitale: 'سنغافورة'),
  Pays(nom: 'سريلانكا', capitale: 'كولومبو'),
  Pays(nom: 'سورية', capitale: 'دمشق'),
  Pays(nom: 'طاجيكستان', capitale: 'دوشنبيه'),
  Pays(nom: 'تايلاند', capitale: 'بانكوك'),
  Pays(nom: 'تيمور الشرقية', capitale: 'ديلي'),
  Pays(nom: 'تركيا', capitale: 'أنقرة'),
  Pays(nom: 'تركمانستان', capitale: 'عشق آباد'),
  Pays(nom: 'الإمارات', capitale: 'أبو ظبي'),
  Pays(nom: 'أوزبكستان', capitale: 'طشقند'),
  Pays(nom: 'فيتنام', capitale: 'هانوي'),
  Pays(nom: 'اليمن', capitale: 'صنعاء'),

  // أوروبا (44)
  Pays(nom: 'ألبانيا', capitale: 'تيرانا'),
  Pays(nom: 'أندورا', capitale: 'أندورا لا فيلا'),
  Pays(nom: 'النمسا', capitale: 'فيينا'),
  Pays(nom: 'بيلاروسيا', capitale: 'مينسك'),
  Pays(nom: 'بلجيكا', capitale: 'بروكسل'),
  Pays(nom: 'البوسنة والهرسك', capitale: 'سراييفو'),
  Pays(nom: 'بلغاريا', capitale: 'صوفيا'),
  Pays(nom: 'كرواتيا', capitale: 'زغرب'),
  Pays(nom: 'تشيكيا', capitale: 'براغ'),
  Pays(nom: 'الدنمارك', capitale: 'كوبنهاغن'),
  Pays(nom: 'إستونيا', capitale: 'تالين'),
  Pays(nom: 'فنلندا', capitale: 'هلسنكي'),
  Pays(nom: 'فرنسا', capitale: 'باريس'),
  Pays(nom: 'ألمانيا', capitale: 'برلين'),
  Pays(nom: 'اليونان', capitale: 'أثينا'),
  Pays(nom: 'المجر', capitale: 'بودابست'),
  Pays(nom: 'آيسلندا', capitale: 'ريكيافيك'),
  Pays(nom: 'إيرلندا', capitale: 'دبلن'),
  Pays(nom: 'إيطاليا', capitale: 'روما'),
  Pays(nom: 'كوسوفو', capitale: 'بريشتينا'),
  Pays(nom: 'لاتفيا', capitale: 'ريغا'),
  Pays(nom: 'ليتوانيا', capitale: 'فيلنيوس'),
  Pays(nom: 'لوكسمبورغ', capitale: 'لوكسمبورغ'),
  Pays(nom: 'مالطا', capitale: 'فاليتا'),
  Pays(nom: 'مولدوفا', capitale: 'كيشيناو'),
  Pays(nom: 'موناكو', capitale: 'موناكو'),
  Pays(nom: 'الجبل الأسود', capitale: 'بودغوريتسا'),
  Pays(nom: 'هولندا', capitale: 'أمستردام'),
  Pays(nom: 'النرويج', capitale: 'أوسلو'),
  Pays(nom: 'بولندا', capitale: 'وارسو'),
  Pays(nom: 'البرتغال', capitale: 'لشبونة'),
  Pays(nom: 'رومانيا', capitale: 'بوخارست'),
  Pays(nom: 'روسيا', capitale: 'موسكو'),
  Pays(nom: 'سان مارينو', capitale: 'سان مارينو'),
  Pays(nom: 'صربيا', capitale: 'بلغراد'),
  Pays(nom: 'سلوفاكيا', capitale: 'براتيسلافا'),
  Pays(nom: 'سلوفينيا', capitale: 'ليوبليانا'),
  Pays(nom: 'إسبانيا', capitale: 'مدريد'),
  Pays(nom: 'السويد', capitale: 'ستوكهولم'),
  Pays(nom: 'سويسرا', capitale: 'برن'),
  Pays(nom: 'أوكرانيا', capitale: 'كييف'),
  Pays(nom: 'المملكة المتحدة', capitale: 'لندن'),
  Pays(nom: 'الفاتيكان', capitale: 'مدينة الفاتيكان'),

  // أمريكا الشمالية (23)
  Pays(nom: 'أنتيغوا وبربودا', capitale: 'سانت جونز'),
  Pays(nom: 'الباهاما', capitale: 'ناسو'),
  Pays(nom: 'باربادوس', capitale: 'بريدجتاون'),
  Pays(nom: 'بليز', capitale: 'بلموبان'),
  Pays(nom: 'كندا', capitale: 'أوتاوا'),
  Pays(nom: 'كوستاريكا', capitale: 'سان خوسيه'),
  Pays(nom: 'كوبا', capitale: 'هافانا'),
  Pays(nom: 'دومينيكا', capitale: 'روسو'),
  Pays(nom: 'جمهورية الدومينيكان', capitale: 'سانتو دومينغو'),
  Pays(nom: 'السلفادور', capitale: 'سان سلفادور'),
  Pays(nom: 'غرينادا', capitale: 'سانت جورجز'),
  Pays(nom: 'غواتيمالا', capitale: 'غواتيمالا سيتي'),
  Pays(nom: 'هايتي', capitale: 'بورت أو برنس'),
  Pays(nom: 'هندوراس', capitale: 'تيغوسيغالبا'),
  Pays(nom: 'جامايكا', capitale: 'كينغستون'),
  Pays(nom: 'المكسيك', capitale: 'مكسيكو سيتي'),
  Pays(nom: 'نيكاراغوا', capitale: 'ماناغوا'),
  Pays(nom: 'بنما', capitale: 'بنما سيتي'),
  Pays(nom: 'سانت كيتس ونيفيس', capitale: 'باستير'),
  Pays(nom: 'سانت لوسيا', capitale: 'كاستريس'),
  Pays(nom: 'سانت فنسنت والغرينادين', capitale: 'كينغستاون'),
  Pays(nom: 'ترينيداد وتوباغو', capitale: 'بورت أوف سبين'),
  Pays(nom: 'الولايات المتحدة', capitale: 'واشنطن'),

  // أمريكا الجنوبية (12)
  Pays(nom: 'الأرجنتين', capitale: 'بوينس آيرس'),
  Pays(nom: 'بوليفيا', capitale: 'سوكره'),
  Pays(nom: 'البرازيل', capitale: 'برازيليا'),
  Pays(nom: 'تشيلي', capitale: 'سانتياغو'),
  Pays(nom: 'كولومبيا', capitale: 'بوغوتا'),
  Pays(nom: 'الإكوادور', capitale: 'كيتو'),
  Pays(nom: 'غيانا', capitale: 'جورج تاون'),
  Pays(nom: 'باراغواي', capitale: 'أسونسيون'),
  Pays(nom: 'بيرو', capitale: 'ليما'),
  Pays(nom: 'سورينام', capitale: 'باراماريبو'),
  Pays(nom: 'أوروغواي', capitale: 'مونتفيدو'),
  Pays(nom: 'فنزويلا', capitale: 'كاراكاس'),

  // أوقيانوسيا (14)
  Pays(nom: 'أستراليا', capitale: 'كانبرا'),
  Pays(nom: 'فيجي', capitale: 'سوفا'),
  Pays(nom: 'كيريباس', capitale: 'تاراوا'),
  Pays(nom: 'جزر مارشال', capitale: 'ماجورو'),
  Pays(nom: 'ميكرونيزيا', capitale: 'بالكير'),
  Pays(nom: 'ناورو', capitale: 'يارين'),
  Pays(nom: 'نيوزيلندا', capitale: 'ويلينغتون'),
  Pays(nom: 'بالاو', capitale: 'ميلكيوك'),
  Pays(nom: 'بابوا غينيا الجديدة', capitale: 'بورت مورسبي'),
  Pays(nom: 'ساموا', capitale: 'أبيا'),
  Pays(nom: 'جزر سليمان', capitale: 'هونيارا'),
  Pays(nom: 'تونغا', capitale: 'نوكوالوفا'),
  Pays(nom: 'توفالو', capitale: 'فونافوتي'),
  Pays(nom: 'فانواتو', capitale: 'بورت فيلا'),
];
