// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXm1LTZg7y4oyGKhAFVNY-iJNl7r0HF4',
    appId: '1:918043121382:web:29a4662af591edf89a8d27',
    messagingSenderId: '918043121382',
    projectId: 'bidaya-app',
    authDomain: 'bidaya-app.firebaseapp.com',
    storageBucket: 'bidaya-app.firebasestorage.app',
    measurementId: 'G-KNS5GNEV6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGT47ExRL-oV0gBZfHXGKQnK1bD5h4lo',
    appId: '1:918043121382:android:bfe051ce3b1461e69a8d27',
    messagingSenderId: '918043121382',
    projectId: 'bidaya-app',
    storageBucket: 'bidaya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAob4SILQOllfE4EfuMQ2XHOmRN_y7LXl4',
    appId: '1:918043121382:ios:f479210a3416ac6b9a8d27',
    messagingSenderId: '918043121382',
    projectId: 'bidaya-app',
    storageBucket: 'bidaya-app.firebasestorage.app',
    iosBundleId: 'com.example.bidaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAob4SILQOllfE4EfuMQ2XHOmRN_y7LXl4',
    appId: '1:918043121382:ios:f479210a3416ac6b9a8d27',
    messagingSenderId: '918043121382',
    projectId: 'bidaya-app',
    storageBucket: 'bidaya-app.firebasestorage.app',
    iosBundleId: 'com.example.bidaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXm1LTZg7y4oyGKhAFVNY-iJNl7r0HF4',
    appId: '1:918043121382:web:80940247c2b756c29a8d27',
    messagingSenderId: '918043121382',
    projectId: 'bidaya-app',
    authDomain: 'bidaya-app.firebaseapp.com',
    storageBucket: 'bidaya-app.firebasestorage.app',
    measurementId: 'G-QNS5LVEN2H',
  );
}
